export const CardTypes = {
  CARDJOBS: 'CARDJOBS',
  PROFILE1: 'CARDPROFILE1',
  PROFILE2: 'CARDPROFILE2',
  PROFILE3: 'CARDPROFILE3',
  PROFILE4: 'CARDPROFILE4',
  STRUCTURAL: 'STRUCTURAL',
  FUNGSIONAL: 'FUNGSIONAL'
}
