/* ========= AUTHENTICATION ========= */
export const AUTHENTICATION_REQUESTED = 'AUTHENTICATION_REQUESTED'
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED'

export const AUTHENTICATION_QR_REQUESTED = 'AUTHENTICATION_QR_REQUESTED'
export const AUTHENTICATION_QR_SUCCESS = 'AUTHENTICATION_QR_SUCCESS'
export const AUTHENTICATION_QR_FAILED = 'AUTHENTICATION_QR_FAILED'

export const AUTHENTICATION_LOGOUT_REQUESTED = 'AUTHENTICATION_LOGOUT_REQUESTED'
export const AUTHENTICATION_LOGOUT_SUCCESS = 'AUTHENTICATION_LOGOUT_SUCCESS'
export const AUTHENTICATION_LOGOUT_FAILED = 'AUTHENTICATION_LOGOUT_FAILED'

export const GET_USER_INFORMATION_REQUESTED = 'GET_USER_INFORMATION_REQUESTED'
export const GET_USER_INFORMATION_SUCCESS = 'GET_USER_INFORMATION_SUCCESS'
export const GET_USER_INFORMATION_FAILED = 'GET_USER_INFORMATION_FAILED'

export const UPDATE_PASSWORD_REQUESTED = 'UPDATE_PASSWORD_REQUESTED'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED'

export const FORGET_PASSWORD_REQUESTED = 'FORGOT_PASSWORD_REQUESTED'
export const FORGET_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGET_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'

export const GET_HASH_URL_PASSWORD_REQUESTED = 'GET_HASH_URL_PASSWORD_REQUESTED'
export const GET_HASH_URL_PASSWORD_SUCCESS = 'GET_HASH_URL_PASSWORD_SUCCESS'
export const GET_HASH_URL_PASSWORD_FAILED = 'GET_HASH_URL_PASSWORD_FAILED'

export const RESET_PASSWORD_REQUESTED = 'RESET_PASSWORD_REQUESTED'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'
/* ========= AUTHENTICATION ========= */

/* ========= PROFILE ========= */
export const UPDATE_PROFILE_REQUESTED = 'UPDATE_PROFILE_REQUESTED'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'
/* ========= PROFILE ========= */

/* ========= USERS  ========= */
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILED = 'GET_USERS_REQUESTED'

export const GET_USER_REQUESTED = 'GET_USER_REQUESTED'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILED = 'GET_USER_REQUESTED'

export const POST_USER_REQUESTED = 'POST_USER_REQUESTED'
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS'
export const POST_USER_FAILED = 'POST_USER_FAILED'

export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'

export const UPDATE_USER_REQUESTED = 'UPDATE_USER_REQUESTED'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

export const CLEAR_USER_STATE = 'CLEAR_USER_STATE'
/* ========= USERS  ========= */

/* ========= ROLE ========== */
export const GET_ROLES_REQUESTED = 'GET_ROLES_REQUESTED'
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS'
export const GET_ROLES_FAILED = 'GET_ROLES_FAILED'

export const GET_ROLES_OPTIONS_REQUESTED = 'GET_ROLES_OPTIONS_REQUESTED'
export const GET_ROLES_OPTIONS_SUCCESS = 'GET_ROLES_OPTIONS_SUCCESS'
export const GET_ROLES_OPTIONS_FAILED = 'GET_ROLES_OPTIONS_FAILED'

export const GET_ROLE_REQUESTED = 'GET_ROLE_REQUESTED'
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS'
export const GET_ROLE_FAILED = 'GET_ROLE_FAILED'

export const POST_ROLE_REQUESTED = 'POST_ROLE_REQUESTED'
export const POST_ROLE_SUCCESS = 'POST_ROLE_SUCCESS'
export const POST_ROLE_FAILED = 'POST_ROLE_FAILED'

export const UPDATE_ROLE_REQUESTED = 'UPDATE_ROLE_REQUESTED'
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS'
export const UPDATE_ROLE_FAILED = 'UPDATE_ROLE_FAILED'

export const DELETE_ROLE_REQUESTED = 'DELETE_ROLE_REQUESTED'
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS'
export const DELETE_ROLE_FAILED = 'DELETE_ROLE_FAILED'

export const GET_PERMISSIONS_REQUESTED = 'GET_PERMISSIONS_REQUESTED'
export const GET_PERMISSIONS_SUCCESS = 'GET_PERMISSIONS_SUCCESS'
export const GET_PERMISSIONS_FAILED = 'GET_PERMISSIONS_FAILED'

export const CLEAR_ROLE_STATE = 'CLEAR_ROLE_STATE'
/* ========= ROLE ========== */

/* ======== EMPLOYEE ========= */
export const GET_EMPLOYEES_REQUESTED = 'GET_EMPLOYEES_REQUESTED'
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS'
export const GET_EMPLOYEES_FAILED = 'GET_EMPLOYEES_FAILED'

export const GET_EMPLOYEE_REQUESTED = 'GET_EMPLOYEE_REQUESTED'
export const GET_EMPLOYEE_SUCCESS = 'GET_EMPLOYEE_SUCCESS'
export const GET_EMPLOYEE_FAILED = 'GET_EMPLOYEE_FAILED'

export const POST_EMPLOYEE_REQUESTED = 'POST_EMPLOYEE_REQUESTED'
export const POST_EMPLOYEE_SUCCESS = 'POST_EMPLOYEE_SUCCESS'
export const POST_EMPLOYEE_FAILED = 'POST_EMPLOYEE_FAILED'

export const UPDATE_EMPLOYEE_REQUESTED = 'UPDATE_EMPLOYEE_REQUESTED'
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_FAILED = 'UPDATE_EMPLOYEE_FAILED'

export const DELETE_EMPLOYEE_REQUESTED = 'DELETE_EMPLOYEE_REQUESTED'
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
export const DELETE_EMPLOYEE_FAILED = 'DELETE_EMPLOYEE_FAILED'
/* ======== EMPLOYEE ========= */

/* ========= CATCH_ERROR ========== */
export const CATCH_ERROR = 'CATCH_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SET_MODAL = 'SET_MODAL'
/* ========= CATCH_ERROR ========== */

/* ======== Responser ======== */
export const ACTION_RESPONSER = 'ACTION_RESPONSER'
/* ======== Responser ======== */
