/* ========= AUTHENTICATION ========= */
export const AUTHENTICATION_REQUESTED = 'AUTHENTICATION_REQUESTED'
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED'

export const AUTHENTICATION_QR_REQUESTED = 'AUTHENTICATION_QR_REQUESTED'
export const AUTHENTICATION_QR_SUCCESS = 'AUTHENTICATION_QR_SUCCESS'
export const AUTHENTICATION_QR_FAILED = 'AUTHENTICATION_QR_FAILED'

export const AUTHENTICATION_LOGOUT_REQUESTED = 'AUTHENTICATION_LOGOUT_REQUESTED'
export const AUTHENTICATION_LOGOUT_SUCCESS = 'AUTHENTICATION_LOGOUT_SUCCESS'
export const AUTHENTICATION_LOGOUT_FAILED = 'AUTHENTICATION_LOGOUT_FAILED'

export const GET_USER_INFORMATION_REQUESTED = 'GET_USER_INFORMATION_REQUESTED'
export const GET_USER_INFORMATION_SUCCESS = 'GET_USER_INFORMATION_SUCCESS'
export const GET_USER_INFORMATION_FAILED = 'GET_USER_INFORMATION_FAILED'

export const UPDATE_PASSWORD_REQUESTED = 'UPDATE_PASSWORD_REQUESTED'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED'

export const FORGET_PASSWORD_REQUESTED = 'FORGOT_PASSWORD_REQUESTED'
export const FORGET_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGET_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'

export const GET_HASH_URL_PASSWORD_REQUESTED = 'GET_HASH_URL_PASSWORD_REQUESTED'
export const GET_HASH_URL_PASSWORD_SUCCESS = 'GET_HASH_URL_PASSWORD_SUCCESS'
export const GET_HASH_URL_PASSWORD_FAILED = 'GET_HASH_URL_PASSWORD_FAILED'

export const RESET_PASSWORD_REQUESTED = 'RESET_PASSWORD_REQUESTED'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'
/* ========= AUTHENTICATION ========= */

/* ========= USER_ME ========= */
export const GET_USER_ME_REQUESTED = 'GET_USER_ME_REQUESTED'
export const GET_USER_ME_SUCCESS = 'GET_USER_ME_SUCCESS'
export const GET_USER_ME_FAILED = 'GET_USER_ME_FAILED'

export const UPDATE_PASSWORD_USER_ME_REQUESTED =
  'UPDATE_PASSWORD_USER_ME_REQUESTED'
export const UPDATE_PASSWORD_USER_ME_SUCCESS = 'UPDATE_PASSWORD_USER_ME_SUCCESS'
export const UPDATE_PASSWORD_USER_ME_FAILED = 'UPDATE_PASSWORD_USER_ME_FAILED'

export const UPDATE_PROFILE_REQUESTED = 'UPDATE_PROFILE_REQUESTED'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'
/* ========= USER_ME ========= */

/* ========= USERS  ========= */
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILED = 'GET_USERS_REQUESTED'

export const GET_USER_REQUESTED = 'GET_USER_REQUESTED'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILED = 'GET_USER_REQUESTED'

export const POST_USER_REQUESTED = 'POST_USER_REQUESTED'
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS'
export const POST_USER_FAILED = 'POST_USER_FAILED'

export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'

export const UPDATE_USER_REQUESTED = 'UPDATE_USER_REQUESTED'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

export const CLEAR_USER_STATE = 'CLEAR_USER_STATE'
/* ========= USERS  ========= */

/* ========= ROLE ========== */
export const GET_ROLES_REQUESTED = 'GET_ROLES_REQUESTED'
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS'
export const GET_ROLES_FAILED = 'GET_ROLES_FAILED'

export const GET_ROLES_OPTIONS_REQUESTED = 'GET_ROLES_OPTIONS_REQUESTED'
export const GET_ROLES_OPTIONS_SUCCESS = 'GET_ROLES_OPTIONS_SUCCESS'
export const GET_ROLES_OPTIONS_FAILED = 'GET_ROLES_OPTIONS_FAILED'

export const GET_ROLE_REQUESTED = 'GET_ROLE_REQUESTED'
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS'
export const GET_ROLE_FAILED = 'GET_ROLE_FAILED'

export const POST_ROLE_REQUESTED = 'POST_ROLE_REQUESTED'
export const POST_ROLE_SUCCESS = 'POST_ROLE_SUCCESS'
export const POST_ROLE_FAILED = 'POST_ROLE_FAILED'

export const UPDATE_ROLE_REQUESTED = 'UPDATE_ROLE_REQUESTED'
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS'
export const UPDATE_ROLE_FAILED = 'UPDATE_ROLE_FAILED'

export const DELETE_ROLE_REQUESTED = 'DELETE_ROLE_REQUESTED'
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS'
export const DELETE_ROLE_FAILED = 'DELETE_ROLE_FAILED'

export const GET_PERMISSIONS_REQUESTED = 'GET_PERMISSIONS_REQUESTED'
export const GET_PERMISSIONS_SUCCESS = 'GET_PERMISSIONS_SUCCESS'
export const GET_PERMISSIONS_FAILED = 'GET_PERMISSIONS_FAILED'

export const CLEAR_ROLE_STATE = 'CLEAR_ROLE_STATE'
/* ========= ROLE ========== */

/* ========= MENU ========== */
export const GET_MENU_REQUESTED = 'GET_MENU_REQUESTED'
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS'
export const GET_MENU_FAILED = 'GET_MENU_FAILED'

export const GET_DETAIL_MENU_REQUESTED = 'GET_DETAIL_MENU_REQUESTED'
export const GET_DETAIL_MENU_SUCCESS = 'GET_DETAIL_MENU_SUCCESS'
export const GET_DETAIL_MENU_FAILED = 'GET_DETAIL_MENU_FAILED'

export const POST_MENU_REQUESTED = 'POST_MENU_REQUESTED'
export const POST_MENU_SUCCESS = 'POST_MENU_SUCCESS'
export const POST_MENU_FAILED = 'POST_MENU_FAILED'

export const DELETE_MENU_REQUESTED = 'DELETE_MENU_REQUESTED'
export const DELETE_MENU_SUCCESS = 'DELETE_MENU_SUCCESS'
export const DELETE_MENU_FAILED = 'DELETE_MENU_FAILED'
/* ========= MENU ========== */

/* ========= PROVIDER ========= */
export const GET_PROVIDER_REQUESTED = 'GET_PROVIDER_REQUESTED'
export const GET_PROVIDER_SUCCESS = 'GET_PROVIDER_SUCCESS'
export const GET_PROVIDER_FAILED = 'GET_PROVIDER_FAILED'

export const POST_PROVIDER_REQUESTED = 'POST_PROVIDER_REQUESTED'
export const POST_PROVIDER_SUCCESS = 'POST_PROVIDER_SUCCESS'
export const POST_PROVIDER_FAILED = 'POST_PROVIDER_FAILED'

export const GET_DETAIL_PROVIDER_REQUESTED = 'GET_DETAIL_PROVIDER_REQUESTED'
export const GET_DETAIL_PROVIDER_SUCCESS = 'GET_DETAIL_PROVIDER_SUCCESS'
export const GET_DETAIL_PROVIDER_FAILED = 'GET_DETAIL_PROVIDER_FAILED'

export const UPDATE_PROVIDER_REQUESTED = 'UPDATE_PROVIDER_REQUESTED'
export const UPDATE_PROVIDER_SUCCESS = 'UPDATE_PROVIDER_SUCCESS'
export const UPDATE_PROVIDER_FAILED = 'UPDATE_PROVIDER_FAILED'

export const DELETE_PROVIDER_REQUESTED = 'DELETE_PROVIDER_REQUESTED'
export const DELETE_PROVIDER_SUCCESS = 'DELETE_PROVIDER_SUCCESS'
export const DELETE_PROVIDER_FAILED = 'DELETE_PROVIDER_FAILED'

export const DELETE_LIST_PROVIDER_REQUESTED = 'DELETE_LIST_PROVIDER_REQUESTED'
export const DELETE_LIST_PROVIDER_SUCCESS = 'DELETE_LIST_PROVIDER_SUCCESS'
export const DELETE_LIST_PROVIDER_FAILED = 'DELETE_LIST_PROVIDER_FAILED'
/* ========= PROVIDER ========= */

/* ========= COURSE ========= */
export const GET_COURSE_REQUESTED = 'GET_COURSE_REQUESTED'
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS'
export const GET_COURSE_FAILED = 'GET_COURSE_FAILED'

export const POST_COURSE_REQUESTED = 'POST_COURSE_REQUESTED'
export const POST_COURSE_SUCCESS = 'POST_COURSE_SUCCESS'
export const POST_COURSE_FAILED = 'POST_COURSE_FAILED'

export const DELETE_COURSE_REQUESTED = 'DELETE_COURSE_REQUESTED'
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS'
export const DELETE_COURSE_FAILED = 'DELETE_COURSE_FAILED'

export const DELETE_COURSE_LIST_REQUESTED = 'DELETE_COURSE_LIST_REQUESTED'
export const DELETE_COURSE_LIST_SUCCESS = 'DELETE_COURSE_LIST_SUCCESS'
export const DELETE_COURSE_LIST_FAILED = 'DELETE_COURSE_LIST_FAILED'

export const GET_DETAIL_COURSE_REQUESTED = 'GET_DETAIL_COURSE_REQUESTED'
export const GET_DETAIL_COURSE_SUCCESS = 'GET_DETAIL_COURSE_SUCCESS'
export const GET_DETAIL_COURSE_FAILED = 'GET_DETAIL_COURSE_FAILED'

export const UPDATE_COURSE_REQUESTED = 'UPDATE_COURSE_REQUESTED'
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS'
export const UPDATE_COURSE_FAILED = 'UPDATE_COURSE_FAILED'

export const FILTER_COURSE_CATEGORY_REQUESTED =
  'FILTER_COURSE_CATEGORY_REQUESTED'
export const FILTER_COURSE_CATEGORY_SUCCESS = 'FILTER_COURSE_CATEGORY_SUCCESS'
export const FILTER_COURSE_CATEGORY_FAILED = 'FILTER_COURSE_CATEGORY_FAILED'

export const FILTER_COURSE_BY_PROVIDER_REQUESTED =
  'FILTER_COURSE_BY_PROVIDER_REQUESTED'
export const FILTER_COURSE_BY_PROVIDER_SUCCESS =
  'FILTER_COURSE_BY_PROVIDER_SUCCESS'
export const FILTER_COURSE_BY_PROVIDER_FAILED =
  'FILTER_COURSE_BY_PROVIDER_FAILED'
/* ========= COURSE ========= */

/* ========= COURSE CATEGORY ========= */
export const GET_COURSE_CATEGORY_REQUESTED = 'GET_COURSE_CATEGORY_REQUESTED'
export const GET_COURSE_CATEGORY_SUCCESS = 'GET_COURSE_CATEGORY_SUCCESS'
export const GET_COURSE_CATEGORY_FAILED = 'GET_COURSE_CATEGORY_FAILED'

export const DELETE_COURSE_CATEGORY_REQUESTED =
  'DELETE_COURSE_CATEGORY_REQUESTED'
export const DELETE_COURSE_CATEGORY_SUCCESS = 'DELETE_COURSE_CATEGORY_SUCCESS'
export const DELETE_COURSE_CATEGORY_FAILED = 'DELETE_COURSE_CATEGORY_FAILED'

export const GET_COURSE_CATEGORY_ID_REQUESTED =
  'GET_COURSE_CATEGORY_ID_REQUESTED'
export const GET_COURSE_CATEGORY_ID_SUCCESS = 'GET_COURSE_CATEGORY_ID_SUCCESS'
export const GET_COURSE_CATEGORY_ID_FAILED = 'GET_COURSE_CATEGORY_ID_FAILED'

export const POST_COURSE_CATEGORY_REQUESTED = 'POST_COURSE_CATEGORY_REQUESTED'
export const POST_COURSE_CATEGORY_SUCCESS = 'POST_COURSE_CATEGORY_SUCCESS'
export const POST_COURSE_CATEGORY_FAILED = 'POST_COURSE_CATEGORY_FAILED'

export const DELETE_COURSE_CATEGORY_LIST_REQUESTED =
  'DELETE_COURSE_CATEGORY_LIST_REQUESTED'
export const DELETE_COURSE_CATEGORY_LIST_SUCCESS =
  'DELETE_COURSE_CATEGORY_LIST_SUCCESS'
export const DELETE_COURSE_CATEGORY_LIST_FAILED =
  'DELETE_COURSE_CATEGORY_LIST_FAILED'

export const UPDATE_COURSE_CATEGORY_REQUESTED =
  'UPDATE_COURSE_CATEGORY_REQUESTED'
export const UPDATE_COURSE_CATEGORY_SUCCESS = 'UPDATE_COURSE_CATEGORY_SUCCESS'
export const UPDATE_COURSE_CATEGORY_FAILED = 'UPDATE_COURSE_CATEGORY_FAILED'

export const GET_PROGRAM_PKASN_REQUESTED = 'GET_PROGRAM_PKASN_REQUESTED'
export const GET_PROGRAM_PKASN_SUCCESS = 'GET_PROGRAM_PKASN_SUCCESS'
export const GET_PROGRAM_PKASN_FAILED = 'GET_PROGRAM_PKASN_FAILED'
/* ========= COURSE CATEGORY ========= */

/* ========= DASHBOARD ========= */
export const DASHBOARD_USER_REQUESTED = 'DASHBOARD_USER_REQUESTED'
export const DASHBOARD_USER_SUCCESS = 'DASHBOARD_USER_SUCCESS'
export const DASHBOARD_USER_FAILED = 'DASHBOARD_USER_FAILED'
/* ========= DASHBOARD ========= */

/* ========= CATCH_ERROR ========== */
export const CATCH_ERROR = 'CATCH_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SET_MODAL = 'SET_MODAL'
/* ========= CATCH_ERROR ========== */

/* ========= COMMAND ========== */
export const GET_COMMAND_TOPIC_REQUESTED = 'GET_COMMAND_TOPIC_REQUESTED'
export const GET_COMMAND_TOPIC_SUCCESS = 'GET_COMMAND_TOPIC_SUCCESS'
export const GET_COMMAND_TOPIC_FAILED = 'GET_COMMAND_TOPIC_FAILED'

export const GET_COMMAND_COURSE_LEVEL_REQUESTED =
  'GET_COMMAND_COURSE_LEVEL_REQUESTED'
export const GET_COMMAND_COURSE_LEVEL_SUCCESS =
  'GET_COMMAND_COURSE_LEVEL_SUCCESS'
export const GET_COMMAND_COURSE_LEVEL_FAILED = 'GET_COMMAND_COURSE_LEVEL_FAILED'

export const GET_COMMAND_COURSE_CATEGORY_REQUESTED =
  'GET_COMMAND_COURSE_CATEGORY_REQUESTED'
export const GET_COMMAND_COURSE_CATEGORY_SUCCESS =
  'GET_COMMAND_COURSE_CATEGORY_SUCCESS'
export const GET_COMMAND_COURSE_CATEGORY_FAILED =
  'GET_COMMAND_COURSE_CATEGORY_FAILED'

export const GET_COMMAND_CATEGORY_REQUESTED = 'GET_COMMAND_CATEGORY_REQUESTED'
export const GET_COMMAND_CATEGORY_SUCCESS = 'GET_COMMAND_CATEGORY_SUCCESS'
export const GET_COMMAND_CATEGORY_FAILED = 'GET_COMMAND_CATEGORY_FAILED'

export const GET_COMMAND_COURSES_REQUESTED = 'GET_COMMAND_COURSES_REQUESTED'
export const GET_COMMAND_COURSES_SUCCESS = 'GET_COMMAND_COURSES_SUCCESS'
export const GET_COMMAND_COURSES_FAILED = 'GET_COMMAND_COURSES_FAILED'

export const GET_COMMAND_MENU_REQUESTED = 'GET_COMMAND_MENU_REQUESTED'
export const GET_COMMAND_MENU_SUCCESS = 'GET_COMMAND_MENU_SUCCESS'
export const GET_COMMAND_MENU_FAILED = 'GET_COMMAND_MENU_FAILED'

export const GET_COMMAND_LANGUAGE_REQUESTED = 'GET_COMMAND_LANGUAGE_REQUESTED'
export const GET_COMMAND_LANGUAGE_SUCCESS = 'GET_COMMAND_LANGUAGE_SUCCESS'
export const GET_COMMAND_LANGUAGE_FAILED = 'GET_COMMAND_LANGUAGE_FAILED'

export const GET_COMMAND_PRICE_REQUESTED = 'GET_COMMAND_PRICE_REQUESTED'
export const GET_COMMAND_PRICE_SUCCESS = 'GET_COMMAND_PRICE_SUCCESS'
export const GET_COMMAND_PRICE_FAILED = 'GET_COMMAND_PRICE_FAILED'

export const GET_COMMAND_ORGANIZER_REQUESTED = 'GET_COMMAND_ORGANIZER_REQUESTED'
export const GET_COMMAND_ORGANIZER_SUCCESS = 'GET_COMMAND_ORGANIZER_SUCCESS'
export const GET_COMMAND_ORGANIZER_FAILED = 'GET_COMMAND_ORGANIZER_FAILED'

export const GET_COMMAND_POSITION_REQUESTED = 'GET_COMMAND_POSITION_REQUESTED'
export const GET_COMMAND_POSITION_SUCCESS = 'GET_COMMAND_POSITION_SUCCESS'
export const GET_COMMAND_POSITION_FAILED = 'GET_COMMAND_POSITION_FAILED'

export const GET_COMMAND_COUPON_REQUESTED = 'GET_COMMAND_COUPON_REQUESTED'
export const GET_COMMAND_COUPON_SUCCESS = 'GET_COMMAND_COUPON_SUCCESS'
export const GET_COMMAND_COUPON_FAILED = 'GET_COMMAND_COUPON_FAILED'

export const GET_COMMAND_ROLES_REQUESTED = 'GET_COMMAND_ROLES_REQUESTED'
export const GET_COMMAND_ROLES_SUCCESS = 'GET_COMMAND_ROLES_SUCCESS'
export const GET_COMMAND_ROLES_FAILED = 'GET_COMMAND_ROLES_FAILED'

export const GET_COMMAND_USER_LEVEL_REQUESTED =
  'GET_COMMAND_USER_LEVEL_REQUESTED'
export const GET_COMMAND_USER_LEVEL_SUCCESS = 'GET_COMMAND_USER_LEVEL_SUCCESS'
export const GET_COMMAND_USER_LEVEL_FAILED = 'GET_COMMAND_USER_LEVEL_FAILED'

export const GET_COMMAND_USER_POSITION_REQUESTED =
  'GET_COMMAND_USER_POSITION_REQUESTED'
export const GET_COMMAND_USER_POSITION_SUCCESS =
  'GET_COMMAND_USER_POSITION_SUCCESS'
export const GET_COMMAND_USER_POSITION_FAILED =
  'GET_COMMAND_USER_POSITION_FAILED'

export const GET_COMMAND_USER_UNIT_REQUESTED = 'GET_COMMAND_USER_UNIT_REQUESTED'
export const GET_COMMAND_USER_UNIT_SUCCESS = 'GET_COMMAND_USER_UNIT_SUCCESS'
export const GET_COMMAND_USER_UNIT_FAILED = 'GET_COMMAND_USER_UNIT_FAILED'

export const GET_COMMAND_CATEGORY_TOPIC_REQUESTED =
  'GET_COMMAND_CATEGORY_TOPIC_REQUESTED'
export const GET_COMMAND_CATEGORY_TOPIC_SUCCESS =
  'GET_COMMAND_CATEGORY_TOPIC_SUCCESS'
export const GET_COMMAND_CATEGORY_TOPIC_FAILED =
  'GET_COMMAND_CATEGORY_TOPIC_FAILED'

export const GET_COMMAND_COURSE_USER_REQUESTED =
  'GET_COMMAND_COURSE_USER_REQUESTED'
export const GET_COMMAND_COURSE_USER_SUCCESS = 'GET_COMMAND_COURSE_USER_SUCCESS'
export const GET_COMMAND_COURSE_USER_FAILED = 'GET_COMMAND_COURSE_USER_FAILED'

export const GET_COMMAND_DURATION_REQUESTED = 'GET_COMMAND_DURATION_REQUESTED'
export const GET_COMMAND_DURATION_SUCCESS = 'GET_COMMAND_DURATION_SUCCESS'
export const GET_COMMAND_DURATION_FAILED = 'GET_COMMAND_DURATION_FAILED'

export const GET_COMMAND_FILTER_COUPON_SUBMISSION_REQUESTED =
  'GET_COMMAND_FILTER_COUPON_SUBMISSION_REQUESTED'
export const GET_COMMAND_FILTER_COUPON_SUBMISSION_SUCCESS =
  'GET_COMMAND_FILTER_COUPON_SUBMISSION_SUCCESS'
export const GET_COMMAND_FILTER_COUPON_SUBMISSION_FAILED =
  'GET_COMMAND_FILTER_COUPON_SUBMISSION_FAILED'
/* ========= COMMAND ========== */

/* ========= ACTIVITY_LOG ========= */
export const GET_ACTIVITY_LOGS_REQUESTED = 'GET_ACTIVITY_LOGS_REQUESTED'
export const GET_ACTIVITY_LOGS_SUCCESS = 'GET_ACTIVITY_LOGS_SUCCESS'
export const GET_ACTIVITY_LOGS_FAILED = 'GET_ACTIVITY_LOGS_FAILED'
/* ========= ACTIVITY_LOG ========= */

/* ========= BANNER ========= */
export const GET_BANNERS_REQUESTED = 'GET_BANNERS_REQUESTED'
export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS'
export const GET_BANNERS_FAILED = 'GET_BANNERS_FAILED'

export const POST_BANNER_REQUESTED = 'POST_BANNER_REQUESTED'
export const POST_BANNER_SUCCESS = 'POST_BANNER_SUCCESS'
export const POST_BANNER_FAILED = 'POST_BANNER_FAILED'

export const GET_BANNER_REQUESTED = 'GET_BANNER_REQUESTED'
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS'
export const GET_BANNER_FAILED = 'GET_BANNER_FAILED'

export const UPDATE_BANNER_REQUESTED = 'UPDATE_BANNER_REQUESTED'
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS'
export const UPDATE_BANNER_FAILED = 'UPDATE_BANNER_FAILED'

export const DELETE_BANNER_REQUESTED = 'DELETE_BANNER_REQUESTED'
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS'
export const DELETE_BANNER_FAILED = 'DELETE_BANNER_FAILED'

export const DELETE_LIST_BANNER_REQUESTED = 'DELETE_LIST_BANNER_REQUESTED'
export const DELETE_LIST_BANNER_SUCCESS = 'DELETE_LIST_BANNER_SUCCESS'
export const DELETE_LIST_BANNER_FAILED = 'DELETE_LIST_BANNER_FAILED'
/* ========= BANNER ========= */

/* ========= BLACKLIST ========= */
export const GET_BLACKLIST_REQUESTED = 'GET_BLACKLIST_REQUESTED'
export const GET_BLACKLIST_SUCCESS = 'GET_BLACKLIST_SUCCESS'
export const GET_BLACKLIST_FAILED = 'GET_BLACKLIST_FAILED'

export const GET_DETAIL_BLACKLIST_REQUESTED = 'GET_DETAIL_BLACKLIST_REQUESTED'
export const GET_DETAIL_BLACKLIST_SUCCESS = 'GET_DETAIL_BLACKLIST_SUCCESS'
export const GET_DETAIL_BLACKLIST_FAILED = 'GET_DETAIL_BLACKLIST_FAILED'

export const OPEN_BLACKLIST_REQUESTED = 'OPEN_BLACKLIST_REQUESTED'
export const OPEN_BLACKLIST_SUCCESS = 'OPEN_BLACKLIST_SUCCESS'
export const OPEN_BLACKLIST_FAILED = 'OPEN_BLACKLIST_FAILED'
/* ========= BLACKLIST ========= */

/* ========= EDITOR CHOICE ========== */
export const GET_EDITOR_CHOICE_REQUESTED = 'GET_EDITOR_CHOICE_REQUESTED'
export const GET_EDITOR_CHOICE_SUCCESS = 'GET_EDITOR_CHOICE_SUCCESS'
export const GET_EDITOR_CHOICE_FAILED = 'GET_EDITOR_CHOICE_FAILED'

export const POST_EDITOR_CHOICE_REQUESTED = 'POST_EDITOR_CHOICE_REQUESTED'
export const POST_EDITOR_CHOICE_SUCCESS = 'POST_EDITOR_CHOICE_SUCCESS'
export const POST_EDITOR_CHOICE_FAILED = 'POST_EDITOR_CHOICE_FAILED'

export const GET_LIST_EDITOR_REQUESTED = 'GET_LIST_EDITOR_REQUESTED'
export const GET_LIST_EDITOR_SUCCESS = 'GET_LIST_EDITOR_SUCCESS'
export const GET_LIST_EDITOR_FAILED = 'GET_LIST_EDITOR_FAILED'
/* ========= EDITOR CHOICE ========== */

/* ========= COUPON ========= */
export const GET_COUPON_REQUESTED = 'GET_COUPON_REQUESTED'
export const GET_COUPON_SUCCESS = 'GET_COUPON_SUCCESS'
export const GET_COUPON_FAILED = 'GET_COUPON_FAILED'

export const GET_DETAIL_COUPON_REQUESTED = 'GET_DETAIL_COUPON_REQUESTED'
export const GET_DETAIL_COUPON_SUCCESS = 'GET_DETAIL_COUPON_SUCCESS'
export const GET_DETAIL_COUPON_FAILED = 'GET_DETAIL_COUPON_FAILED'

export const POST_COUPON_REQUESTED = 'POST_COUPON_REQUESTED'
export const POST_COUPON_SUCCESS = 'POST_COUPON_SUCCESS'
export const POST_COUPON_FAILED = 'POST_COUPON_FAILED'

export const DELETE_COUPON_REQUESTED = 'DELETE_COUPON_REQUESTED'
export const DELETE_COUPON_SUCCESS = 'DELETE_COUPON_SUCCESS'
export const DELETE_COUPON_FAILED = 'DELETE_COUPON_FAILED'

export const UPDATE_COUPON_REQUESTED = 'UPDATE_COUPON_REQUESTED'
export const UPDATE_COUPON_SUCCESS = 'UPDATE_COUPON_SUCCESS'
export const UPDATE_COUPON_FAILED = 'UPDATE_COUPON_FAILED'

export const DELETE_COUPON_LIST_REQUESTED = 'DELETE_COUPON_LIST_REQUESTED'
export const DELETE_COUPON_LIST_SUCCESS = 'DELETE_COUPON_LIST_SUCCESS'
export const DELETE_COUPON_LIST_FAILED = 'DELETE_COUPON_LIST_FAILED'
/* ========= COUPON ========= */

/* ========= Coupon Submission ========= */
export const GET_COUPON_SUBMISSION_REQUESTED = 'GET_COUPON_SUBMISSION_REQUESTED'
export const GET_COUPON_SUBMISSION_SUCCESS = 'GET_COUPON_SUBMISSION_SUCCESS'
export const GET_COUPON_SUBMISSION_FAILED = 'GET_COUPON_SUBMISSION_FAILED'

export const GET_DETAIL_COUPON_SUBMISSION_REQUESTED =
  'GET_DETAIL_COUPON_SUBMISSION_REQUESTED'
export const GET_DETAIL_COUPON_SUBMISSION_SUCCESS =
  'GET_DETAIL_COUPON_SUBMISSION_SUCCESS'
export const GET_DETAIL_COUPON_SUBMISSION_FAILED =
  'GET_DETAIL_COUPON_SUBMISSION_FAILED'

export const REJECT_COUPON_SUBMISSION_REQUESTED =
  'REJECT_COUPON_SUBMISSION_REQUESTED'
export const REJECT_COUPON_SUBMISSION_SUCCESS =
  'REJECT_COUPON_SUBMISSION_SUCCESS'
export const REJECT_COUPON_SUBMISSION_FAILED = 'REJECT_COUPON_SUBMISSION_FAILED'

export const APPROVE_COUPON_SUBMISSION_REQUESTED =
  'APPROVE_COUPON_SUBMISSION_REQUESTED'
export const APPROVE_COUPON_SUBMISSION_SUCCESS =
  'APPROVE_COUPON_SUBMISSION_SUCCESS'
export const APPROVE_COUPON_SUBMISSION_FAILED =
  'APPROVE_COUPON_SUBMISSION_FAILED'

export const REJECT_COUPON_SUBMISSION_LIST_REQUESTED =
  'REJECT_COUPON_SUBMISSION_LIST_REQUESTED'
export const REJECT_COUPON_SUBMISSION_LIST_SUCCESS =
  'REJECT_COUPON_SUBMISSION_LIST_SUCCESS'
export const REJECT_COUPON_SUBMISSION_LIST_FAILED =
  'REJECT_COUPON_SUBMISSION_LIST_FAILED'

export const APPROVE_COUPON_SUBMISSION_LIST_REQUSTED =
  'APPROVE_COUPON_SUBMISSION_LIST_REQUSTED'
export const APPROVE_COUPON_SUBMISSION_LIST_SUCCESS =
  'APPROVE_COUPON_SUBMISSION_LIST_SUCCESS'
export const APPROVE_COUPON_SUBMISSION_LIST_FAILED =
  'APPROVE_COUPON_SUBMISSION_LIST_FAILED'
/* ========= Coupon Submission ========= */

/* ========= UPDATE PROVIDER =========== */
export const UPDATE_PROVIDER_BULK_REQUESTED = 'UPDATE_PROVIDER_BULK_REQUESTED'
export const UPDATE_PROVIDER_BULK_SUCCESS = 'UPDATE_PROVIDER_BULK_SUCCESS'
export const UPDATE_PROVIDER_BULK_FAILED = 'UPDATE_PROVIDER_BULK_FAILED'
/* ========= UPDATE PROVIDER =========== */

/* ========= UPDATE PROVIDER ========== */
export const GET_UPDATE_PROVIDER_REQUESTED = 'GET_UPDATE_PROVIDER_REQUESTED'
export const GET_UPDATE_PROVIDER_SUCCESS = 'GET_UPDATE_PROVIDER_SUCCESS'
export const GET_UPDATE_PROVIDER_FAILED = 'GET_UPDATE_PROVIDER_FAILED'
/* ========= UPDATE PROVIDER ========== */

/* ========= BULK COURSE ========= */
export const PATCH_BULK_COURSE_REQUESTED = 'PATCH_BULK_COURSE_REQUESTED'
export const PATCH_BULK_COURSE_SUCCESS = 'PATCH_BULK_COURSE_SUCCESS'
export const PATCH_BULK_COURSE_FAILED = 'PATCH_BULK_COURSE_FAILED'
/* ========= BULK COURSE ========= */

/* ========= SORT_BANNER ========= */
export const GET_SORT_BANNER_REQUESTED = 'GET_SORT_BANNER_REQUESTED'
export const GET_SORT_BANNER_SUCCESS = 'GET_SORT_BANNER_SUCCESS'
export const GET_SORT_BANNER_FAILED = 'GET_SORT_BANNER_FAILED'

export const PATCH_SORT_BANNER_REQUESTED = 'PATCH_SORT_BANNER_REQUESTED'
export const PATCH_SORT_BANNER_SUCCESS = 'PATCH_SORT_BANNER_SUCCESS'
export const PATCH_SORT_BANNER_FAILED = 'PATCH_SORT_BANNER_FAILED'
/* ========= SORT_BANNER ========= */

/* ========= EXCEL Import ======== */

/* ========= Module User ========= */
export const IMPORT_EXCEL_USER_BLACKLIST_REQUESTED =
  'IMPORT_EXCEL_USER_BLACKLIST_REQUESTED'
export const IMPORT_EXCEL_USER_BLACKLIST_SUCCESS =
  'IMPORT_EXCEL_USER_BLACKLIST_SUCCESS'
export const IMPORT_EXCEL_USER_BLACKLIST_FAILED =
  'IMPORT_EXCEL_USER_BLACKLIST_FAILED'

export const IMPORT_EXCEL_USER_REQUESTED = 'IMPORT_EXCEL_USER_REQUESTED'
export const IMPORT_EXCEL_USER_SUCCESS = 'IMPORT_EXCEL_USER_SUCCESS'
export const IMPORT_EXCEL_USER_FAILED = 'IMPORT_EXCEL_USER_FAILED'

export const IMPORT_EXCEL_USER_LEVEL_REQUESTED =
  'IMPORT_EXCEL_USER_LEVEL_REQUESTED'
export const IMPORT_EXCEL_USER_LEVEL_SUCCESS = 'IMPORT_EXCEL_USER_LEVEL_SUCCESS'
export const IMPORT_EXCEL_USER_LEVEL_FAILED = 'IMPORT_EXCEL_USER_LEVEL_FAILED'

export const EXPORT_EXCEL_USER_BLACKLIST_REQUESTED =
  'EXPORT_EXCEL_USER_BLACKLIST_REQUESTED'
export const EXPORT_EXCEL_USER_BLACKLIST_SUCCESS =
  'EXPORT_EXCEL_USER_BLACKLIST_SUCCESS'
export const EXPORT_EXCEL_USER_BLACKLIST_FAILED =
  'EXPORT_EXCEL_USER_BLACKLIST_FAILED'

export const EXPORT_EXCEL_USER_REQUESTED = 'EXPORT_EXCEL_USER_REQUESTED'
export const EXPORT_EXCEL_USER_SUCCESS = 'EXPORT_EXCEL_USER_SUCCESS'
export const EXPORT_EXCEL_USER_FAILED = 'EXPORT_EXCEL_USER_FAILED'

export const EXPORT_EXCEL_USER_LEVEL_REQUESTED =
  'EXPORT_EXCEL_USER_LEVEL_REQUESTED'
export const EXPORT_EXCEL_USER_LEVEL_SUCCESS = 'EXPORT_EXCEL_USER_LEVEL_SUCCESS'
export const EXPORT_EXCEL_USER_LEVEL_FAILED = 'EXPORT_EXCEL_USER_LEVEL_FAILED'

export const EXPORT_EXCEL_USER_LIST_REQUESTED =
  'EXPORT_EXCEL_USER_LIST_REQUESTED'
export const EXPORT_EXCEL_USER_LIST_SUCCESS = 'EXPORT_EXCEL_USER_LIST_SUCCESS'
export const EXPORT_EXCEL_USER_LIST_FAILED = 'EXPORT_EXCEL_USER_LIST_FAILED'
/* ========= Module User ========= */

/* ========= Coupon ========== */
export const IMPORT_EXCEL_COUPON_REQUESTED = 'IMPORT_EXCEL_COUPON_REQUESTED'
export const IMPORT_EXCEL_COUPON_SUCCESS = 'IMPORT_EXCEL_COUPON_SUCCESS'
export const IMPORT_EXCEL_COUPON_FAILED = 'IMPORT_EXCEL_COUPON_FAILED'

export const EXPORT_EXCEL_COUPON_REQUESTED = 'EXPORT_EXCEL_COUPON_REQUESTED'
export const EXPORT_EXCEL_COUPON_SUCCESS = 'EXPORT_EXCEL_COUPON_SUCCESS'
export const EXPORT_EXCEL_COUPON_FAILED = 'EXPORT_EXCEL_COUPON_FAILED'

export const EXPORT_REPORT_COUPON_REQUESTED = 'EXPORT_REPORT_COUPON_REQUESTED'
export const EXPORT_REPORT_COUPON_SUCCESS = 'EXPORT_REPORT_COUPON_SUCCESS'
export const EXPORT_REPORT_COUPON_FAILED = 'EXPORT_REPORT_COUPON_FAILED'
/* ========= Coupon ========== */

/* ========= EXCEL Import ======== */

/* ======== Notification =========== */
export const GET_NOTIFICATION_REQUESTED = 'GET_NOTIFICATION_REQUESTED'
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS'
export const GET_NOTIFICATION_FAILED = 'GET_NOTIFICATION_FAILED'

export const POST_NOTIFICATION_REQUESTED = 'POST_NOTIFICATION_REQUESTED'
export const POST_NOTIFICATION_SUCCESS = 'POST_NOTIFICATION_SUCCESS'
export const POST_NOTIFICATION_FAILED = 'POST_NOTIFICATION_FAILED'
/* ======== Notification =========== */

/* ======== Responser ======== */
export const ACTION_RESPONSER = 'ACTION_RESPONSER'
/* ======== Responser ======== */

/* ======== Notification ========= */
export const SET_NOTIFICATION = 'SET_NOTIFICATION'
/* ======== Notification ========= */

/* ======== EMPLOYEE ========= */
export const GET_EMPLOYEES_REQUESTED = 'GET_EMPLOYEES_REQUESTED'
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS'
export const GET_EMPLOYEES_FAILED = 'GET_EMPLOYEES_FAILED'

export const GET_EMPLOYEE_REQUESTED = 'GET_EMPLOYEE_REQUESTED'
export const GET_EMPLOYEE_SUCCESS = 'GET_EMPLOYEE_SUCCESS'
export const GET_EMPLOYEE_FAILED = 'GET_EMPLOYEE_FAILED'

export const POST_EMPLOYEE_REQUESTED = 'POST_EMPLOYEE_REQUESTED'
export const POST_EMPLOYEE_SUCCESS = 'POST_EMPLOYEE_SUCCESS'
export const POST_EMPLOYEE_FAILED = 'POST_EMPLOYEE_FAILED'

export const UPDATE_EMPLOYEE_REQUESTED = 'UPDATE_EMPLOYEE_REQUESTED'
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_FAILED = 'UPDATE_EMPLOYEE_FAILED'

export const DELETE_EMPLOYEE_REQUESTED = 'DELETE_EMPLOYEE_REQUESTED'
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
export const DELETE_EMPLOYEE_FAILED = 'DELETE_EMPLOYEE_FAILED'
/* ======== EMPLOYEE ========= */
