/* ========= DASHBOARD ========= */
export const SUMMARIES_REQUESTED = 'SUMMARIES_REQUESTED'
export const SUMMARIES_SUCCESS = 'SUMMARIES_SUCCESS'
export const SUMMARIES_FAILED = 'SUMMARIES_FAILED'
/* ========= DASHBOARD ========= */

/* ========= REKAPITULASI ========= */
export const GET_COMPOSITION_REQUESTED = 'GET_COMPOSITION_REQUESTED'
export const GET_COMPOSITION_SUCCESS = 'GET_COMPOSITION_SUCCESS'
export const GET_COMPOSITION_FAILED = 'GET_COMPOSITION_FAILED'

export const GET_COMPOSITION_CATEGORY_REQUESTED =
  'GET_COMPOSITION_CATEGORY_REQUESTED'
export const GET_COMPOSITION_CATEGORY_SUCCESS =
  'GET_COMPOSITION_CATEGORY_SUCCESS'
export const GET_COMPOSITION_CATEGORY_FAILED = 'GET_COMPOSITION_CATEGORY_FAILED'

export const GET_ASN_RECAP_REQUESTED = 'GET_ASN_RECAP_REQUESTED'
export const GET_ASN_RECAP_SUCCESS = 'GET_ASN_RECAP_SUCCESS'
export const GET_ASN_RECAP_FAILED = 'GET_ASN_RECAP_FAILED'

export const GET_ASN_RECAP_CATEGORY_REQUESTED =
  'GET_ASN_RECAP_CATEGORY_REQUESTED'
export const GET_ASN_RECAP_CATEGORY_SUCCESS = 'GET_ASN_RECAP_CATEGORY_SUCCESS'
export const GET_ASN_RECAP_CATEGORY_FAILED = 'GET_ASN_RECAP_CATEGORY_FAILED'

export const GET_NON_ASN_RECAP_REQUESTED = 'GET_NON_ASN_RECAP_REQUESTED'
export const GET_NON_ASN_RECAP_SUCCESS = 'GET_NON_ASN_RECAP_SUCCESS'
export const GET_NON_ASN_RECAP_FAILED = 'GET_NON_ASN_RECAP_FAILED'

export const GET_NON_ASN_RECAP_CATEGORY_REQUESTED =
  'GET_NON_ASN_RECAP_CATEGORY_REQUESTED'
export const GET_NON_ASN_RECAP_CATEGORY_SUCCESS =
  'GET_NON_ASN_RECAP_CATEGORY_SUCCESS'
export const GET_NON_ASN_RECAP_CATEGORY_FAILED =
  'GET_NON_ASN_RECAP_CATEGORY_FAILED'

export const GET_OUTSOURCE_RECAP_REQUESTED = 'GET_OUTSOURCE_RECAP_REQUESTED'
export const GET_OUTSOURCE_RECAP_SUCCESS = 'GET_OUTSOURCE_RECAP_SUCCESS'
export const GET_OUTSOURCE_RECAP_FAILED = 'GET_OUTSOURCE_RECAP_FAILED'

export const GET_OUTSOURCE_RECAP_CATEGORY_REQUESTED =
  'GET_OUTSOURCE_RECAP_CATEGORY_REQUESTED'
export const GET_OUTSOURCE_RECAP_CATEGORY_SUCCESS =
  'GET_OUTSOURCE_RECAP_CATEGORY_SUCCESS'
export const GET_OUTSOURCE_RECAP_CATEGORY_FAILED =
  'GET_OUTSOURCE_RECAP_CATEGORY_FAILED'

export const GET_EMPLOYEES_RECAP_REQUESTED = 'GET_EMPLOYEES_RECAP_REQUESTED'
export const GET_EMPLOYEES_RECAP_SUCCESS = 'GET_EMPLOYEES_RECAP_SUCCESS'
export const GET_EMPLOYEES_RECAP_FAILED = 'GET_EMPLOYEES_RECAP_FAILED'

export const CLEAR_EMPLOYEES_RECAP = 'CLEAR_EMPLOYEES_RECAP'
/* ========= REKAPITULASI ========= */

/* ========= COMPARE ========= */
export const GET_NOTES_REQUESTED = 'GET_NOTES_REQUESTED'
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS'
export const GET_NOTES_FAILED = 'GET_NOTES_FAILED'

export const UPDATE_NOTES_REQUESTED = 'UPDATE_NOTES_REQUESTED'
export const UPDATE_NOTES_SUCCESS = 'UPDATE_NOTES_SUCCESS'
export const UPDATE_NOTES_FAILED = 'UPDATE_NOTES_FAILED'
/* ========= COMPARE ========= */

/* ========= AUTHENTICATION ========= */
export const AUTHENTICATION_REQUESTED = 'AUTHENTICATION_REQUESTED'
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED'

export const AUTHENTICATION_QR_REQUESTED = 'AUTHENTICATION_QR_REQUESTED'
export const AUTHENTICATION_QR_SUCCESS = 'AUTHENTICATION_QR_SUCCESS'
export const AUTHENTICATION_QR_FAILED = 'AUTHENTICATION_QR_FAILED'

export const AUTHENTICATION_LOGOUT_REQUESTED = 'AUTHENTICATION_LOGOUT_REQUESTED'
export const AUTHENTICATION_LOGOUT_SUCCESS = 'AUTHENTICATION_LOGOUT_SUCCESS'
export const AUTHENTICATION_LOGOUT_FAILED = 'AUTHENTICATION_LOGOUT_FAILED'

export const GET_USER_INFORMATION_REQUESTED = 'GET_USER_INFORMATION_REQUESTED'
export const GET_USER_INFORMATION_SUCCESS = 'GET_USER_INFORMATION_SUCCESS'
export const GET_USER_INFORMATION_FAILED = 'GET_USER_INFORMATION_FAILED'

export const UPDATE_PASSWORD_REQUESTED = 'UPDATE_PASSWORD_REQUESTED'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED'

export const FORGET_PASSWORD_REQUESTED = 'FORGOT_PASSWORD_REQUESTED'
export const FORGET_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGET_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'

export const GET_HASH_URL_PASSWORD_REQUESTED = 'GET_HASH_URL_PASSWORD_REQUESTED'
export const GET_HASH_URL_PASSWORD_SUCCESS = 'GET_HASH_URL_PASSWORD_SUCCESS'
export const GET_HASH_URL_PASSWORD_FAILED = 'GET_HASH_URL_PASSWORD_FAILED'

export const RESET_PASSWORD_REQUESTED = 'RESET_PASSWORD_REQUESTED'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'

export const NEW_PASSWORD_REQUESTED = 'NEW_PASSWORD_REQUESTED'
export const NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS'
export const NEW_PASSWORD_FAILED = 'NEW_PASSWORD_FAILED'
/* ========= AUTHENTICATION ========= */

/* ========= PROFILE ========= */
export const GET_PROFILE_REQUESTED = 'GET_PROFILE_REQUESTED'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED'

export const UPDATE_PROFILE_REQUESTED = 'UPDATE_PROFILE_REQUESTED'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'
/* ========= PROFILE ========= */

/* ========= EMPLOYEE COMPARE ========= */
export const GET_COMPARE_USERS_REQUESTED = 'GET_COMPARE_USERS_REQUESTED'
export const GET_COMPARE_USERS_SUCCESS = 'GET_COMPARE_USERS_SUCCESS'
export const GET_COMPARE_USERS_FAILED = 'GET_COMPARE_USERS_FAILED'
/* ========= EMPLOYEE COMPARE ========= */

/* ========= EMPLOYEE PROMOTION ========= */
export const GET_UNOCCUPIED_POSITIONS_REQUESTED =
  'GET_UNOCCUPIED_POSITIONS_REQUESTED'
export const GET_UNOCCUPIED_POSITIONS_SUCCESS =
  'GET_UNOCCUPIED_POSITIONS_SUCCESS'
export const GET_UNOCCUPIED_POSITIONS_FAILED = 'GET_UNOCCUPIED_POSITIONS_FAILED'

export const GET_UNOCCUPIED_POSITIONS_DETAILS_REQUESTED =
  'GET_UNOCCUPIED_POSITIONS_DETAILS_REQUESTED'
export const GET_UNOCCUPIED_POSITIONS_DETAILS_SUCCESS =
  'GET_UNOCCUPIED_POSITIONS_DETAILS_SUCCESS'
export const GET_UNOCCUPIED_POSITIONS_DETAILS_FAILED =
  'GET_UNOCCUPIED_POSITIONS_DETAILS_FAILED'

export const GET_BRIEF_USERS_REQUESTED = 'GET_BRIEF_USERS_REQUESTED'
export const GET_BRIEF_USERS_SUCCESS = 'GET_BRIEF_USERS_SUCCESS'
export const GET_BRIEF_USERS_FAILED = 'GET_BRIEF_USERS_FAILED'

export const GET_PROMOTION_USERS_REQUESTED = 'GET_PROMOTION_USERS_REQUESTED'
export const GET_PROMOTION_USERS_SUCCESS = 'GET_PROMOTION_USERS_SUCCESS'
export const GET_PROMOTION_USERS_FAILED = 'GET_PROMOTION_USERS_FAILED'
/* ========= EMPLOYEE PROMOTION ========= */

/* ======== EMPLOYEE ========= */
export const GET_EMPLOYEES_REQUESTED = 'GET_EMPLOYEES_REQUESTED'
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS'
export const GET_EMPLOYEES_FAILED = 'GET_EMPLOYEES_FAILED'

export const GET_EMPLOYEE_REQUESTED = 'GET_EMPLOYEE_REQUESTED'
export const GET_EMPLOYEE_SUCCESS = 'GET_EMPLOYEE_SUCCESS'
export const GET_EMPLOYEE_FAILED = 'GET_EMPLOYEE_FAILED'

export const POST_EMPLOYEE_REQUESTED = 'POST_EMPLOYEE_REQUESTED'
export const POST_EMPLOYEE_SUCCESS = 'POST_EMPLOYEE_SUCCESS'
export const POST_EMPLOYEE_FAILED = 'POST_EMPLOYEE_FAILED'

export const UPDATE_EMPLOYEE_REQUESTED = 'UPDATE_EMPLOYEE_REQUESTED'
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_FAILED = 'UPDATE_EMPLOYEE_FAILED'

export const SYNC_EMPLOYEES_REQUESTED = 'SYNC_EMPLOYEES_REQUESTED'
export const SYNC_EMPLOYEES_SUCCESS = 'SYNC_EMPLOYEES_SUCCESS'
export const SYNC_EMPLOYEES_FAILED = 'SYNC_EMPLOYEES_FAILED'

export const DOWNLOAD_TEMPLATE_REQUESTED = 'DOWNLOAD_TEMPLATE_REQUESTED'
export const DOWNLOAD_TEMPLATE_SUCCESS = 'DOWNLOAD_TEMPLATE_SUCCESS'
export const DOWNLOAD_TEMPLATE_FAILED = 'DOWNLOAD_TEMPLATE_FAILED'

export const UPLOAD_TEMPLATE_REQUESTED = 'UPLOAD_TEMPLATE_REQUESTED'
export const UPLOAD_TEMPLATE_SUCCESS = 'UPLOAD_TEMPLATE_SUCCESS'
export const UPLOAD_TEMPLATE_FAILED = 'UPLOAD_TEMPLATE_FAILED'

export const GET_ACTIVITIES_REQUESTED = 'GET_ACTIVITIES_REQUESTED'
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS'
export const GET_ACTIVITIES_FAILED = 'GET_ACTIVITIES_FAILED'

export const UPDATE_EMPLOYEE_STATUS_REQUESTED =
  'UPDATE_EMPLOYEE_STATUS_REQUESTED'
export const UPDATE_EMPLOYEE_STATUS_SUCCESS = 'UPDATE_EMPLOYEE_STATUS_SUCCESS'
export const UPDATE_EMPLOYEE_STATUS_FAILED = 'UPDATE_EMPLOYEE_STATUS_FAILED'

export const DELETE_EMPLOYEE_REQUESTED = 'DELETE_EMPLOYEE_REQUESTED'
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
export const DELETE_EMPLOYEE_FAILED = 'DELETE_EMPLOYEE_FAILED'

export const DOWNLOAD_LOG_ERROR_REQUESTED = 'DOWNLOAD_LOG_ERROR_REQUESTED'
export const DOWNLOAD_LOG_ERROR_SUCCESS = 'DOWNLOAD_LOG_ERROR_SUCCESS'
export const DOWNLOAD_LOG_ERROR_FAILED = 'DOWNLOAD_LOG_ERROR_FAILED'

export const CLEAR_EMPLOYEE_STATE = 'CLEAR_EMPLOYEE_STATE'
export const CLEAR_TEMPLATE_UPLOAD = 'CLEAR_TEMPLATE_UPLOAD'
export const CLEAR_TEMPLATE = 'CLEAR_TEMPLATE'
export const CLEAR_LOG = 'CLEAR_LOG'
/* ======== EMPLOYEE ========= */

/* ======== ECHELON ========= */
export const GET_ECHELONS_OPTIONS_REQUESTED = 'GET_ECHELONS_OPTIONS_REQUESTED'
export const GET_ECHELONS_OPTIONS_SUCCESS = 'GET_ECHELONS_OPTIONS_SUCCESS'
export const GET_ECHELONS_OPTIONS_FAILED = 'GET_ECHELONS_OPTIONS_FAILED'

export const GET_ECHELONS_REQUESTED = 'GET_ECHELONS_REQUESTED'
export const GET_ECHELONS_SUCCESS = 'GET_ECHELONS_SUCCESS'
export const GET_ECHELONS_FAILED = 'GET_ECHELONS_FAILED'

export const GET_ECHELON_REQUESTED = 'GET_ECHELON_REQUESTED'
export const GET_ECHELON_SUCCESS = 'GET_ECHELON_SUCCESS'
export const GET_ECHELON_FAILED = 'GET_ECHELON_FAILED'

export const POST_ECHELON_REQUESTED = 'POST_ECHELON_REQUESTED'
export const POST_ECHELON_SUCCESS = 'POST_ECHELON_SUCCESS'
export const POST_ECHELON_FAILED = 'POST_ECHELON_FAILED'

export const UPDATE_ECHELON_REQUESTED = 'UPDATE_ECHELON_REQUESTED'
export const UPDATE_ECHELON_SUCCESS = 'UPDATE_ECHELON_SUCCESS'
export const UPDATE_ECHELON_FAILED = 'UPDATE_ECHELON_FAILED'

export const DELETE_ECHELON_REQUESTED = 'DELETE_ECHELON_REQUESTED'
export const DELETE_ECHELON_SUCCESS = 'DELETE_ECHELON_SUCCESS'
export const DELETE_ECHELON_FAILED = 'DELETE_ECHELON_FAILED'

export const CLEAR_ECHELON_STATE = 'CLEAR_ECHELON_STATE'
/* ======== ECHELON ========= */

/* ======== POSITION ========= */
export const GET_POSITIONS_ORDERS_REQUESTED = 'GET_POSITIONS_ORDERS_REQUESTED'
export const GET_POSITIONS_ORDERS_SUCCESS = 'GET_POSITIONS_ORDERS_SUCCESS'
export const GET_POSITIONS_ORDERS_FAILED = 'GET_POSITIONS_ORDERS_FAILED'

export const GET_POSITIONS_REQUESTED = 'GET_POSITIONS_REQUESTED'
export const GET_POSITIONS_SUCCESS = 'GET_POSITIONS_SUCCESS'
export const GET_POSITIONS_FAILED = 'GET_POSITIONS_FAILED'

export const GET_POSITION_REQUESTED = 'GET_POSITION_REQUESTED'
export const GET_POSITION_SUCCESS = 'GET_POSITION_SUCCESS'
export const GET_POSITION_FAILED = 'GET_POSITION_FAILED'

export const POST_POSITION_REQUESTED = 'POST_POSITION_REQUESTED'
export const POST_POSITION_SUCCESS = 'POST_POSITION_SUCCESS'
export const POST_POSITION_FAILED = 'POST_POSITION_FAILED'

export const UPDATE_POSITION_REQUESTED = 'UPDATE_POSITION_REQUESTED'
export const UPDATE_POSITION_SUCCESS = 'UPDATE_POSITION_SUCCESS'
export const UPDATE_POSITION_FAILED = 'UPDATE_POSITION_FAILED'

export const DELETE_POSITION_REQUESTED = 'DELETE_POSITION_REQUESTED'
export const DELETE_POSITION_SUCCESS = 'DELETE_POSITION_SUCCESS'
export const DELETE_POSITION_FAILED = 'DELETE_POSITION_FAILED'

export const CLEAR_POSITION_STATE = 'CLEAR_POSITION_STATE'

export const GET_POSITIONS_HISTORIES_REQUESTED =
  'GET_POSITIONS_HISTORIES_REQUESTED'
export const GET_POSITIONS_HISTORIES_SUCCESS = 'GET_POSITIONS_HISTORIES_SUCCESS'
export const GET_POSITIONS_HISTORIES_FAILED = 'GET_POSITIONS_HISTORIES_FAILED'

export const GET_POSITION_HISTORIES_REQUESTED =
  'GET_POSITION_HISTORIES_REQUESTED'
export const GET_POSITION_HISTORIES_SUCCESS = 'GET_POSITION_HISTORIES_SUCCESS'
export const GET_POSITION_HISTORIES_FAILED = 'GET_POSITION_HISTORIES_FAILED'

export const POST_POSITION_HISTORIES_REQUESTED =
  'POST_POSITION_HISTORIES_REQUESTED'
export const POST_POSITION_HISTORIES_SUCCESS = 'POST_POSITION_HISTORIES_SUCCESS'
export const POST_POSITION_HISTORIES_FAILED = 'POST_POSITION_HISTORIES_FAILED'

export const UPDATE_POSITION_HISTORIES_REQUESTED =
  'UPDATE_POSITION_HISTORIES_REQUESTED'
export const UPDATE_POSITION_HISTORIES_SUCCESS =
  'UPDATE_POSITION_HISTORIES_SUCCESS'
export const UPDATE_POSITION_HISTORIES_FAILED =
  'UPDATE_POSITION_HISTORIES_FAILED'

export const DELETE_POSITION_HISTORIES_REQUESTED =
  'DELETE_POSITION_HISTORIES_REQUESTED'
export const DELETE_POSITION_HISTORIES_SUCCESS =
  'DELETE_POSITION_HISTORIES_SUCCESS'
export const DELETE_POSITION_HISTORIES_FAILED =
  'DELETE_POSITION_HISTORIES_FAILED'

export const CLEAR_POSITION_HISTORIES_STATE = 'CLEAR_POSITION_HISTORIES_STATE'
/* ======== POSITION ========= */

/* ======== GRADE ========= */
export const GET_GRADES_OPTIONS_REQUESTED = 'GET_GRADES_OPTIONS_REQUESTED'
export const GET_GRADES_OPTIONS_SUCCESS = 'GET_GRADES_OPTIONS_SUCCESS'
export const GET_GRADES_OPTIONS_FAILED = 'GET_GRADES_OPTIONS_FAILED'

export const GET_GRADES_REQUESTED = 'GET_GRADES_REQUESTED'
export const GET_GRADES_SUCCESS = 'GET_GRADES_SUCCESS'
export const GET_GRADES_FAILED = 'GET_GRADES_FAILED'

export const GET_GRADE_REQUESTED = 'GET_GRADE_REQUESTED'
export const GET_GRADE_SUCCESS = 'GET_GRADE_SUCCESS'
export const GET_GRADE_FAILED = 'GET_GRADE_FAILED'

export const POST_GRADE_REQUESTED = 'POST_GRADE_REQUESTED'
export const POST_GRADE_SUCCESS = 'POST_GRADE_SUCCESS'
export const POST_GRADE_FAILED = 'POST_GRADE_FAILED'

export const UPDATE_GRADE_REQUESTED = 'UPDATE_GRADE_REQUESTED'
export const UPDATE_GRADE_SUCCESS = 'UPDATE_GRADE_SUCCESS'
export const UPDATE_GRADE_FAILED = 'UPDATE_GRADE_FAILED'

export const DELETE_GRADE_REQUESTED = 'DELETE_GRADE_REQUESTED'
export const DELETE_GRADE_SUCCESS = 'DELETE_GRADE_SUCCESS'
export const DELETE_GRADE_FAILED = 'DELETE_GRADE_FAILED'

export const CLEAR_GRADE_STATE = 'CLEAR_GRADE_STATE'
/* ======== GRADE ========= */

/* ======== TRAINING ========= */
export const GET_TRAININGS_REQUESTED = 'GET_TRAININGS_REQUESTED'
export const GET_TRAININGS_SUCCESS = 'GET_TRAININGS_SUCCESS'
export const GET_TRAININGS_FAILED = 'GET_TRAININGS_FAILED'

export const GET_TRAINING_REQUESTED = 'GET_TRAINING_REQUESTED'
export const GET_TRAINING_SUCCESS = 'GET_TRAINING_SUCCESS'
export const GET_TRAINING_FAILED = 'GET_TRAINING_FAILED'

export const POST_TRAINING_REQUESTED = 'POST_TRAINING_REQUESTED'
export const POST_TRAINING_SUCCESS = 'POST_TRAINING_SUCCESS'
export const POST_TRAINING_FAILED = 'POST_TRAINING_FAILED'

export const UPDATE_TRAINING_REQUESTED = 'UPDATE_TRAINING_REQUESTED'
export const UPDATE_TRAINING_SUCCESS = 'UPDATE_TRAINING_SUCCESS'
export const UPDATE_TRAINING_FAILED = 'UPDATE_TRAINING_FAILED'

export const DELETE_TRAINING_REQUESTED = 'DELETE_TRAINING_REQUESTED'
export const DELETE_TRAINING_SUCCESS = 'DELETE_TRAINING_SUCCESS'
export const DELETE_TRAINING_FAILED = 'DELETE_TRAINING_FAILED'

export const GET_LEVELS_REQUESTED = 'GET_LEVELS_REQUESTED'
export const GET_LEVELS_SUCCESS = 'GET_LEVELS_SUCCESS'
export const GET_LEVELS_FAILED = 'GET_LEVELS_FAILED'

export const GET_CLUSTERS_REQUESTED = 'GET_CLUSTERS_REQUESTED'
export const GET_CLUSTERS_SUCCESS = 'GET_CLUSTERS_SUCCESS'
export const GET_CLUSTERS_FAILED = 'GET_CLUSTERS_FAILED'

export const CLEAR_TRAINING_STATE = 'CLEAR_TRAINING_STATE'
/* ======== TRAINING ========= */

/* ======== RECOGNITION ========= */
export const GET_RECOGNITIONS_OPTIONS_REQUESTED =
  'GET_RECOGNITIONS_OPTIONS_REQUESTED'
export const GET_RECOGNITIONS_OPTIONS_SUCCESS =
  'GET_RECOGNITIONS_OPTIONS_SUCCESS'
export const GET_RECOGNITIONS_OPTIONS_FAILED = 'GET_RECOGNITIONS_OPTIONS_FAILED'

export const GET_RECOGNITIONS_REQUESTED = 'GET_RECOGNITIONS_REQUESTED'
export const GET_RECOGNITIONS_SUCCESS = 'GET_RECOGNITIONS_SUCCESS'
export const GET_RECOGNITIONS_FAILED = 'GET_RECOGNITIONS_FAILED'

export const GET_RECOGNITION_REQUESTED = 'GET_RECOGNITION_REQUESTED'
export const GET_RECOGNITION_SUCCESS = 'GET_RECOGNITION_SUCCESS'
export const GET_RECOGNITION_FAILED = 'GET_RECOGNITION_FAILED'

export const POST_RECOGNITION_REQUESTED = 'POST_RECOGNITION_REQUESTED'
export const POST_RECOGNITION_SUCCESS = 'POST_RECOGNITION_SUCCESS'
export const POST_RECOGNITION_FAILED = 'POST_RECOGNITION_FAILED'

export const UPDATE_RECOGNITION_REQUESTED = 'UPDATE_RECOGNITION_REQUESTED'
export const UPDATE_RECOGNITION_SUCCESS = 'UPDATE_RECOGNITION_SUCCESS'
export const UPDATE_RECOGNITION_FAILED = 'UPDATE_RECOGNITION_FAILED'

export const DELETE_RECOGNITION_REQUESTED = 'DELETE_RECOGNITION_REQUESTED'
export const DELETE_RECOGNITION_SUCCESS = 'DELETE_RECOGNITION_SUCCESS'
export const DELETE_RECOGNITION_FAILED = 'DELETE_RECOGNITION_FAILED'

export const CLEAR_RECOGNITION_STATE = 'CLEAR_RECOGNITION_STATE'
/* ======== RECOGNITION ========= */

/* ======== TARGET ========= */
export const GET_TARGETS_REQUESTED = 'GET_TARGETS_REQUESTED'
export const GET_TARGETS_SUCCESS = 'GET_TARGETS_SUCCESS'
export const GET_TARGETS_FAILED = 'GET_TARGETS_FAILED'

export const GET_TARGET_REQUESTED = 'GET_TARGET_REQUESTED'
export const GET_TARGET_SUCCESS = 'GET_TARGET_SUCCESS'
export const GET_TARGET_FAILED = 'GET_TARGET_FAILED'

export const POST_TARGET_REQUESTED = 'POST_TARGET_REQUESTED'
export const POST_TARGET_SUCCESS = 'POST_TARGET_SUCCESS'
export const POST_TARGET_FAILED = 'POST_TARGET_FAILED'

export const UPDATE_TARGET_REQUESTED = 'UPDATE_TARGET_REQUESTED'
export const UPDATE_TARGET_SUCCESS = 'UPDATE_TARGET_SUCCESS'
export const UPDATE_TARGET_FAILED = 'UPDATE_TARGET_FAILED'

export const DELETE_TARGET_REQUESTED = 'DELETE_TARGET_REQUESTED'
export const DELETE_TARGET_SUCCESS = 'DELETE_TARGET_SUCCESS'
export const DELETE_TARGET_FAILED = 'DELETE_TARGET_FAILED'

export const CLEAR_TARGET_STATE = 'CLEAR_TARGET_STATE'
/* ======== TARGET ========= */

/* ======== PERFORMANCE ========= */
export const GET_PERFORMANCES_REQUESTED = 'GET_PERFORMANCES_REQUESTED'
export const GET_PERFORMANCES_SUCCESS = 'GET_PERFORMANCES_SUCCESS'
export const GET_PERFORMANCES_FAILED = 'GET_PERFORMANCES_FAILED'

export const GET_PERFORMANCE_REQUESTED = 'GET_PERFORMANCE_REQUESTED'
export const GET_PERFORMANCE_SUCCESS = 'GET_PERFORMANCE_SUCCESS'
export const GET_PERFORMANCE_FAILED = 'GET_PERFORMANCE_FAILED'

export const POST_PERFORMANCE_REQUESTED = 'POST_PERFORMANCE_REQUESTED'
export const POST_PERFORMANCE_SUCCESS = 'POST_PERFORMANCE_SUCCESS'
export const POST_PERFORMANCE_FAILED = 'POST_PERFORMANCE_FAILED'

export const UPDATE_PERFORMANCE_REQUESTED = 'UPDATE_PERFORMANCE_REQUESTED'
export const UPDATE_PERFORMANCE_SUCCESS = 'UPDATE_PERFORMANCE_SUCCESS'
export const UPDATE_PERFORMANCE_FAILED = 'UPDATE_PERFORMANCE_FAILED'

export const DELETE_PERFORMANCE_REQUESTED = 'DELETE_PERFORMANCE_REQUESTED'
export const DELETE_PERFORMANCE_SUCCESS = 'DELETE_PERFORMANCE_SUCCESS'
export const DELETE_PERFORMANCE_FAILED = 'DELETE_PERFORMANCE_FAILED'

export const CLEAR_PERFORMANCE_STATE = 'CLEAR_PERFORMANCE_STATE'
/* ======== PERFORMANCE ========= */

/* ======== DISCIPLINARY ========= */
export const GET_DISCIPLINARIES_REQUESTED = 'GET_DISCIPLINARIES_REQUESTED'
export const GET_DISCIPLINARIES_SUCCESS = 'GET_DISCIPLINARIES_SUCCESS'
export const GET_DISCIPLINARIES_FAILED = 'GET_DISCIPLINARIES_FAILED'

export const GET_DISCIPLINARIES_OPTIONS_REQUESTED =
  'GET_DISCIPLINARIES_OPTIONS_REQUESTED'
export const GET_DISCIPLINARIES_OPTIONS_SUCCESS =
  'GET_DISCIPLINARIES_OPTIONS_SUCCESS'
export const GET_DISCIPLINARIES_OPTIONS_FAILED =
  'GET_DISCIPLINARIES_OPTIONS_FAILED'

export const GET_DISCIPLINARY_REQUESTED = 'GET_DISCIPLINARY_REQUESTED'
export const GET_DISCIPLINARY_SUCCESS = 'GET_DISCIPLINARY_SUCCESS'
export const GET_DISCIPLINARY_FAILED = 'GET_DISCIPLINARY_FAILED'

export const POST_DISCIPLINARY_REQUESTED = 'POST_DISCIPLINARY_REQUESTED'
export const POST_DISCIPLINARY_SUCCESS = 'POST_DISCIPLINARY_SUCCESS'
export const POST_DISCIPLINARY_FAILED = 'POST_DISCIPLINARY_FAILED'

export const UPDATE_DISCIPLINARY_REQUESTED = 'UPDATE_DISCIPLINARY_REQUESTED'
export const UPDATE_DISCIPLINARY_SUCCESS = 'UPDATE_DISCIPLINARY_SUCCESS'
export const UPDATE_DISCIPLINARY_FAILED = 'UPDATE_DISCIPLINARY_FAILED'

export const DELETE_DISCIPLINARY_REQUESTED = 'DELETE_DISCIPLINARY_REQUESTED'
export const DELETE_DISCIPLINARY_SUCCESS = 'DELETE_DISCIPLINARY_SUCCESS'
export const DELETE_DISCIPLINARY_FAILED = 'DELETE_DISCIPLINARY_FAILED'

export const CLEAR_DISCIPLINARY_STATE = 'CLEAR_DISCIPLINARY_STATE'
/* ======== DISCIPLINARY ========= */

/* ======== MASTER DATA ========= */

/* ========= USERS  ========= */
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILED = 'GET_USERS_REQUESTED'

export const GET_USER_REQUESTED = 'GET_USER_REQUESTED'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILED = 'GET_USER_REQUESTED'

export const POST_USER_REQUESTED = 'POST_USER_REQUESTED'
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS'
export const POST_USER_FAILED = 'POST_USER_FAILED'

export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'

export const UPDATE_USER_REQUESTED = 'UPDATE_USER_REQUESTED'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

export const UPDATE_USER_STATUS_REQUESTED = 'UPDATE_USER_STATUS_REQUESTED'
export const UPDATE_USER_STATUS_SUCCESS = 'UPDATE_USER_STATUS_SUCCESS'
export const UPDATE_USER_STATUS_FAILED = 'UPDATE_USER_STATUS_FAILED'

export const CLEAR_USER_STATE = 'CLEAR_USER_STATE'
/* ========= USERS  ========= */

/* ========= ROLE ========== */
export const GET_ROLES_REQUESTED = 'GET_ROLES_REQUESTED'
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS'
export const GET_ROLES_FAILED = 'GET_ROLES_FAILED'

export const GET_ROLES_OPTIONS_REQUESTED = 'GET_ROLES_OPTIONS_REQUESTED'
export const GET_ROLES_OPTIONS_SUCCESS = 'GET_ROLES_OPTIONS_SUCCESS'
export const GET_ROLES_OPTIONS_FAILED = 'GET_ROLES_OPTIONS_FAILED'

export const GET_ROLE_REQUESTED = 'GET_ROLE_REQUESTED'
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS'
export const GET_ROLE_FAILED = 'GET_ROLE_FAILED'

export const POST_ROLE_REQUESTED = 'POST_ROLE_REQUESTED'
export const POST_ROLE_SUCCESS = 'POST_ROLE_SUCCESS'
export const POST_ROLE_FAILED = 'POST_ROLE_FAILED'

export const UPDATE_ROLE_REQUESTED = 'UPDATE_ROLE_REQUESTED'
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS'
export const UPDATE_ROLE_FAILED = 'UPDATE_ROLE_FAILED'

export const DELETE_ROLE_REQUESTED = 'DELETE_ROLE_REQUESTED'
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS'
export const DELETE_ROLE_FAILED = 'DELETE_ROLE_FAILED'

export const GET_PERMISSIONS_REQUESTED = 'GET_PERMISSIONS_REQUESTED'
export const GET_PERMISSIONS_SUCCESS = 'GET_PERMISSIONS_SUCCESS'
export const GET_PERMISSIONS_FAILED = 'GET_PERMISSIONS_FAILED'

export const CLEAR_ROLE_STATE = 'CLEAR_ROLE_STATE'
/* ========= ROLE ========== */

/* ======== INSTITUTION ========= */
export const GET_INSTITUTIONS_REQUESTED = 'GET_INSTITUTIONS_REQUESTED'
export const GET_INSTITUTIONS_SUCCESS = 'GET_INSTITUTIONS_SUCCESS'
export const GET_INSTITUTIONS_FAILED = 'GET_INSTITUTIONS_FAILED'

export const GET_INSTITUTIONS_OPTIONS_REQUESTED =
  'GET_INSTITUTIONS_OPTIONS_REQUESTED'
export const GET_INSTITUTIONS_OPTIONS_SUCCESS =
  'GET_INSTITUTIONS_OPTIONS_SUCCESS'
export const GET_INSTITUTIONS_OPTIONS_FAILED = 'GET_INSTITUTIONS_OPTIONS_FAILED'

export const GET_INSTITUTION_REQUESTED = 'GET_INSTITUTION_REQUESTED'
export const GET_INSTITUTION_SUCCESS = 'GET_INSTITUTION_SUCCESS'
export const GET_INSTITUTION_FAILED = 'GET_INSTITUTION_FAILED'

export const POST_INSTITUTION_REQUESTED = 'POST_INSTITUTION_REQUESTED'
export const POST_INSTITUTION_SUCCESS = 'POST_INSTITUTION_SUCCESS'
export const POST_INSTITUTION_FAILED = 'POST_INSTITUTION_FAILED'

export const UPDATE_INSTITUTION_REQUESTED = 'UPDATE_INSTITUTION_REQUESTED'
export const UPDATE_INSTITUTION_SUCCESS = 'UPDATE_INSTITUTION_SUCCESS'
export const UPDATE_INSTITUTION_FAILED = 'UPDATE_INSTITUTION_FAILED'

export const DELETE_INSTITUTION_REQUESTED = 'DELETE_INSTITUTION_REQUESTED'
export const DELETE_INSTITUTION_SUCCESS = 'DELETE_INSTITUTION_SUCCESS'
export const DELETE_INSTITUTION_FAILED = 'DELETE_INSTITUTION_FAILED'

export const CLEAR_INSTITUTION_STATE = 'CLEAR_INSTITUTION_STATE'
/* ======== INSTITUTION ========= */

/* ======== EMPLOYMENT TYPE ========= */
export const GET_EMPLOYMENT_TYPES_OPTIONS_REQUESTED =
  'GET_EMPLOYMENT_TYPES_OPTIONS_REQUESTED'
export const GET_EMPLOYMENT_TYPES_OPTIONS_SUCCESS =
  'GET_EMPLOYMENT_TYPES_OPTIONS_SUCCESS'
export const GET_EMPLOYMENT_TYPES_OPTIONS_FAILED =
  'GET_EMPLOYMENT_TYPES_OPTIONS_FAILED'

export const GET_EMPLOYMENT_TYPES_REQUESTED = 'GET_EMPLOYMENT_TYPES_REQUESTED'
export const GET_EMPLOYMENT_TYPES_SUCCESS = 'GET_EMPLOYMENT_TYPES_SUCCESS'
export const GET_EMPLOYMENT_TYPES_FAILED = 'GET_EMPLOYMENT_TYPES_FAILED'

export const GET_EMPLOYMENT_TYPE_REQUESTED = 'GET_EMPLOYMENT_TYPE_REQUESTED'
export const GET_EMPLOYMENT_TYPE_SUCCESS = 'GET_EMPLOYMENT_TYPE_SUCCESS'
export const GET_EMPLOYMENT_TYPE_FAILED = 'GET_EMPLOYMENT_TYPE_FAILED'

export const POST_EMPLOYMENT_TYPE_REQUESTED = 'POST_EMPLOYMENT_TYPE_REQUESTED'
export const POST_EMPLOYMENT_TYPE_SUCCESS = 'POST_EMPLOYMENT_TYPE_SUCCESS'
export const POST_EMPLOYMENT_TYPE_FAILED = 'POST_EMPLOYMENT_TYPE_FAILED'

export const UPDATE_EMPLOYMENT_TYPE_REQUESTED =
  'UPDATE_EMPLOYMENT_TYPE_REQUESTED'
export const UPDATE_EMPLOYMENT_TYPE_SUCCESS = 'UPDATE_EMPLOYMENT_TYPE_SUCCESS'
export const UPDATE_EMPLOYMENT_TYPE_FAILED = 'UPDATE_EMPLOYMENT_TYPE_FAILED'

export const DELETE_EMPLOYMENT_TYPE_REQUESTED =
  'DELETE_EMPLOYMENT_TYPE_REQUESTED'
export const DELETE_EMPLOYMENT_TYPE_SUCCESS = 'DELETE_EMPLOYMENT_TYPE_SUCCESS'
export const DELETE_EMPLOYMENT_TYPE_FAILED = 'DELETE_EMPLOYMENT_TYPE_FAILED'

export const CLEAR_EMPLOYMENT_TYPE_STATE = 'CLEAR_EMPLOYMENT_TYPE_STATE'
/* ======== EMPLOYMENT TYPE ========= */

/* ======== DECREE ========= */
export const GET_DECREES_REQUESTED = 'GET_DECREES_REQUESTED'
export const GET_DECREES_SUCCESS = 'GET_DECREES_SUCCESS'
export const GET_DECREES_FAILED = 'GET_DECREES_FAILED'

export const CLEAR_DECREE_STATE = 'CLEAR_DECREE_STATE'
/* ======== DECREE ========= */

/* ======== RESIDENCE ========= */
export const GET_RESIDENCES_REQUESTED = 'GET_RESIDENCES_REQUESTED'
export const GET_RESIDENCES_SUCCESS = 'GET_RESIDENCES_SUCCESS'
export const GET_RESIDENCES_FAILED = 'GET_RESIDENCES_FAILED'

export const CLEAR_RESIDENCE_STATE = 'CLEAR_RESIDENCE_STATE'
/* ======== RESIDENCE ========= */

/* ======== GROUP ========= */
export const GET_GROUPS_REQUESTED = 'GET_GROUPS_REQUESTED'
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS'
export const GET_GROUPS_FAILED = 'GET_GROUPS_FAILED'

export const CLEAR_GROUP_STATE = 'CLEAR_GROUP_STATE'
/* ======== GROUP ========= */

/* ======== MASTER DATA ========= */

/* ======== RECAPITULATION ========= */
/* ======== DIAGRAMS ========= */
export const GET_DIAGRAMS_REQUESTED = 'GET_DIAGRAMS_REQUESTED'
export const GET_DIAGRAMS_SUCCESS = 'GET_DIAGRAMS_SUCCESS'
export const GET_DIAGRAMS_FAILED = 'GET_DIAGRAMS_FAILED'

export const EXPORT_DIAGRAMS_REQUESTED = 'EXPORT_DIAGRAMS_REQUESTED'
export const EXPORT_DIAGRAMS_SUCCESS = 'EXPORT_DIAGRAMS_SUCCESS'
export const EXPORT_DIAGRAMS_FAILED = 'EXPORT_DIAGRAMS_FAILED'

export const CLEAR_DIAGRAMS_STATE = 'CLEAR_DIAGRAMS_STATE'
export const CLEAR_DIAGRAMS_EXPORT_STATE = 'CLEAR_DIAGRAMS_EXPORT_STATE'
/* ======== DIAGRAMS ========= */
/* ======== RECAPITULATION ========= */

/* ======== EXPORT ========= */
export const EXPORT_RECAP_REQUESTED = 'EXPORT_RECAP_REQUESTED'
export const EXPORT_RECAP_SUCCESS = 'EXPORT_RECAP_SUCCESS'
export const EXPORT_RECAP_FAILED = 'EXPORT_RECAP_FAILED'

export const EXPORT_EMPLOYEES_REQUESTED = 'EXPORT_EMPLOYEES_REQUESTED'
export const EXPORT_EMPLOYEES_SUCCESS = 'EXPORT_EMPLOYEES_SUCCESS'
export const EXPORT_EMPLOYEES_FAILED = 'EXPORT_EMPLOYEES_FAILED'

export const EXPORT_EMPLOYEES_PREVIEW_REQUESTED =
  'EXPORT_EMPLOYEES_PREVIEW_REQUESTED'
export const EXPORT_EMPLOYEES_PREVIEW_SUCCESS =
  'EXPORT_EMPLOYEES_PREVIEW_SUCCESS'
export const EXPORT_EMPLOYEES_PREVIEW_FAILED = 'EXPORT_EMPLOYEES_PREVIEW_FAILED'

export const EXPORT_EMPLOYEE_DETAIL_REQUESTED =
  'EXPORT_EMPLOYEE_DETAIL_REQUESTED'
export const EXPORT_EMPLOYEE_DETAIL_SUCCESS = 'EXPORT_EMPLOYEE_DETAIL_SUCCESS'
export const EXPORT_EMPLOYEE_DETAIL_FAILED = 'EXPORT_EMPLOYEE_DETAIL_FAILED'

export const EXPORT_DRH_REQUESTED = 'EXPORT_DRH_REQUESTED'
export const EXPORT_DRH_SUCCESS = 'EXPORT_DRH_SUCCESS'
export const EXPORT_DRH_FAILED = 'EXPORT_DRH_FAILED'

export const EXPORT_COMPARISON_REQUESTED = 'EXPORT_COMPARISON_REQUESTED'
export const EXPORT_COMPARISON_SUCCESS = 'EXPORT_COMPARISON_SUCCESS'
export const EXPORT_COMPARISON_FAILED = 'EXPORT_COMPARISON_FAILED'

export const EXPORT_PROMOTION_REQUESTED = 'EXPORT_PROMOTION_REQUESTED'
export const EXPORT_PROMOTION_SUCCESS = 'EXPORT_PROMOTION_SUCCESS'
export const EXPORT_PROMOTION_FAILED = 'EXPORT_PROMOTION_FAILED'

export const CLEAR_EXPORT_EMPLOYEES_PREVIEW_STATE =
  'CLEAR_EXPORT_EMPLOYEES_PREVIEW_STATE'
export const CLEAR_EXPORT_EMPLOYEES_STATE = 'CLEAR_EXPORT_EMPLOYEES_STATE'
export const CLEAR_EXPORT_EMPLOYEE_DETAIL_STATE =
  'CLEAR_EXPORT_EMPLOYEE_DETAIL_STATE'
export const CLEAR_EXPORT_DRH_STATE = 'CLEAR_EXPORT_DRH_STATE'
export const CLEAR_EXPORT_RECAP_STATE = 'CLEAR_EXPORT_RECAP_STATE'
export const CLEAR_EXPORT_COMPARISON_STATE = 'CLEAR_EXPORT_COMPARISON_STATE'
export const CLEAR_EXPORT_PROMOTION_STATE = 'CLEAR_EXPORT_PROMOTION_STATE'
/* ======== EXPORT ========= */

/* ========= CATCH_ERROR ========== */
export const CATCH_ERROR = 'CATCH_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SET_MODAL = 'SET_MODAL'
/* ========= CATCH_ERROR ========== */

/* ======== Responser ======== */
export const ACTION_RESPONSER = 'ACTION_RESPONSER'
/* ======== Responser ======== */
